apiVersion: batch/v1
kind: Job
metadata:
  name: kube-hunter
spec:
  template:
    spec:
      containers:
      - name: kube-hunter
        image: 127.0.0.1:5000/kube-hunter:latest
        command: ["python", "kube-hunter.py"]
        args: ["--pod","--report","json"]
      restartPolicy: Never
  backoffLimit: 4
